### PR TITLE
add FlxTwinkleEffect. Handy for showing invincible state.

### PR DESCRIPTION
**Pull request by intersrc**

### CODE REVIEW

**Comment by starry-abyss** [comment]
What is the difference with http://api.haxeflixel.com/flixel/effects/FlxFlicker.html ?

**Comment by SeiferTim** [comment]
@starry-abyss it looks like this actually flashes the sprite White, instead of transparent (if I'm reading it right)

**Comment by JoeCreates** [comment]
From the looks of the code I think this won't work on native due to the use
of the mask on copypixels?

**Comment by intersrc** [comment]
@JoeCreates You are right. I'll try to solve it.

**Comment by intersrc** [comment]
@JoeCreates Not perfect, but enough for pixel games.

**Comment by intersrc** [comment]
@starry-abyss As @SeiferTim said, it can flash the sprite a specific color. And the color can be translucent, like `0x7fff0000`

**Comment by Gama11** [comment]
There's a few code style issues here, and `#if cpp` is incorrect. It would have to be `#if sys` to also work on Neko. Not sure about HTML5 with WebGL rendering.

Besides, is that workaround even necessary anymore with OpenFL 8?

**Pull request closed without merging**
