### PR TITLE
Stop-gap to allow saving screenshots on non-flash

### PR DESCRIPTION
**Pull request by IBwWG**
Since the current default is broken, not having a save dialog to use on non-flash platforms, this added presetPath feature gives you a way out.

### CODE REVIEW

**Comment by Gama11** [comment]
Travis was failing here on Flash:

```
haxelib run openfl build coverage flash -Dcoverage1
/home/travis/build/HaxeFlixel/flixel-addons/flixel/addons/plugin/screengrab/FlxScreenGrab.hx:220: characters 6-10 : Unknown identifier : path
/home/travis/build/HaxeFlixel/flixel-addons/flixel/addons/plugin/screengrab/FlxScreenGrab.hx:220: characters 20-24 : Unknown identifier : path
/home/travis/build/HaxeFlixel/flixel-addons/flixel/addons/plugin/screengrab/FlxScreenGrab.hx:221: characters 3-13 : Unknown identifier : writerFunc
/home/travis/build/HaxeFlixel/flixel-addons/flixel/addons/plugin/screengrab/FlxScreenGrab.hx:221: characters 14-18 : Unknown identifier : path
```

Could you update the PR branch? There've been some changes to the Travis config.

**Comment by IBwWG** [comment]
OK, I'll have to have a look at it later.

**Comment by Gama11** [comment]
Any news?

**Comment by IBwWG** [comment]
Not yet, it may be a few weeks before I have a chance to look at it again.  Sorry :(

**Comment by IBwWG** [comment]
Travis is passing now, it seems.

**Comment by Gama11** [comment]
Not going to need a workaround for legacy anymore now that we have OpenFL 8 support.

**Pull request closed without merging**
