### PR TITLE
Optional Graphic for new backdrop

### PR DESCRIPTION
**Pull request by Tembac**
This is a really simple change. On FlxSprite the graphic is optional because we can load it later. I think the same must be done for backdrops because we can load the graphic later, as i'm doing on my game.

### CODE REVIEW

**Comment by Gama11** [comment]
Have you checked that `draw()` can deal with a null graphic? I don't see any checks there.

**Comment by Tembac** [comment]
I'm not sure why it shows 2 commits because I only made the changes from the second commit. Is this normal?

**Comment by Gama11** [comment]
Are you sure `draw()` is fine with this in all cases? In the `FlxG.renderBlit` section, it accesses `graphic` without a null check for example.

**Comment by Gama11** [comment]
Yeah, doesn't really look like this has been tested, crashes on both renderers.

**Comment by Tembac** [comment]
Ups, Sorry. I though it was like that because I loaded the graphic immediately.
Thanks for fixing it!

**Pull request closed without merging**
