### PR TITLE
Error handling for uninitialized array

### PR DESCRIPTION
**Pull request by xerosugar**
in case the tilemap does not contain the specified 'tileIndices'

### CODE REVIEW

**Comment by Gama11** [comment]
Somehow there are merge conflicts?

**Comment by xerosugar** [comment]
I assumed it was... but it says "This branch is 2 commits ahead, 614 commits behind HaxeFlixel:dev." so I guess not. not sure what to do. do I need to do git pull or something?

**Comment by Gama11** [comment]
Probably simpler if I quickly do it for such a small change.

**Comment by xerosugar** [comment]
thanks

**Pull request closed without merging**
