### PR TITLE
FlxFSM: fix an invalid field access error on Neko

### PR DESCRIPTION
**Pull request by alihassan0**
`map.exists(null);` breaks the application on neko .. 
so as a workaround I check if the parameters is not null first

### CODE REVIEW

**Comment by Gama11** [comment]
Looks like you accidentally added the changes from #254 as well here?

**Comment by alihassan0** [comment]
I branch before I fixed this .. but i think I forget that means all my past commits are there too 
should I close this and create a new one ?

**Comment by Gama11** [comment]
You could also revert that commit.

**Comment by Gama11** [comment]
Thanks!

**Pull request merged**
