### PR TITLE
Add sourceRect and fillCenter properties

### PR DESCRIPTION
**Pull request by Beeblerox**
`sourceRect` will allow users to define which part of image to use as a source for slicing.
`fillCenter` might help to save performance for cases when you don't need to fill center part of sliced sprite (leave it empty)

### CODE REVIEW

**Comment by Gama11** [comment]
There's a lot of unrelated whitespace changes in the diff - we use [haxe-formatter](https://github.com/HaxeCheckstyle/haxe-formatter) now.

**Comment by Beeblerox** [comment]
i'm sorry about that. didn't noticed them.
Hope that my second commit fixed it

**Comment by Gama11** [comment]
Does this close #275?

**Comment by Beeblerox** [comment]
it should, but i'd wait response from @Geokureli

**Pull request merged**
